
SRC_PREFIX=es_lect1_

BUILD_DIR=build

all:
	@echo "choose target ex1"

ex1: $(SRC_PREFIX)ex1.c
	-mkdir -p $(BUILD_DIR)
	gcc $(SRC_PREFIX)ex1.c -o $(BUILD_DIR)/ex1

clean:
	-rm -rf $(BUILD_DIR)
