NAME=lab1a
CC=gcc
CFLAGS=-Wall

all: ex1 ex2 ex3

ex1:
	$(CC) $(CFLAGS) $(NAME)_ex1.c -o $(NAME)_ex1

ex2:
	$(CC) $(CFLAGS) $(NAME)_ex2.c -o $(NAME)_ex2

ex3:
	$(CC) $(CFLAGS) $(NAME)_ex3.c -o $(NAME)_ex3

clean:
	-rm $(NAME)_ex1.exe $(NAME)_ex2.exe $(NAME)_ex3.exe
